export const ORDER_STATUSES = [
    'PENDING',
    'ACCEPTED_AT_BRANCH',
    'IN_SORTING',
    'IN_TRANSIT',
    'PLACED_IN_LOCKER',
    'READY_FOR_BRANCH_PICKUP',
    'OUT_FOR_DELIVERY',
    'DELIVERED',
    'PICKED_UP_BY_CUSTOMER',
    'RETURN_TO_SENDER',
    'CANCELLED'
];

export const DELIVERY_METHODS = [
    'HOME_DELIVERY',
    'BRANCH_PICKUP',
    'LOCKER_PICKUP'
];